#ifndef ENUM_STEP_HPP
#define ENUM_STEP_HPP
enum enum_step {
  STEP_WAIT_INIT,
  STEP_INIT,
  STEP_WAIT_FINISH,
  STEP_FINISH,

  STEP_WAIT_ACCELERATE,
  STEP_ACCELERATE,
  STEP_WAIT_DECELERATE,
  STEP_DECELERATE,

  STEP_WAIT_SPEED_BASE_START,
  STEP_SPEED_BASE_START,
  STEP_WAIT_SPEED_BASE_STOP,
  STEP_SPEED_BASE_STOP,

  STEP_WAIT_TRACKER_LEFT_START,
  STEP_TRACKER_LEFT_START,
  STEP_WAIT_TRACKER_LEFT_DETECTED,
  STEP_TRACKER_LEFT_DETECTED,
  STEP_WAIT_TRACKER_LEFT_RETURN,
  STEP_TRACKER_LEFT_RETURN,

  STEP_WAIT_TRACKER_RIGHT_START,
  STEP_TRACKER_RIGHT_START,
  STEP_WAIT_TRACKER_RIGHT_DETECTED,
  STEP_TRACKER_RIGHT_DETECTED,
  STEP_WAIT_TRACKER_RIGHT_RETURN,
  STEP_TRACKER_RIGHT_RETURN,

  STEP_WAIT_TRACKER_BOTH_START,
  STEP_TRACKER_BOTH_START,
  STEP_WAIT_TRACKER_BOTH_DETECTED,
  STEP_TRACKER_BOTH_DETECTED,
  STEP_WAIT_TRACKER_BOTH_RETURN,
  STEP_TRACKER_BOTH_RETURN,

  STEP_WAIT_TRACKER_MOTOR_LEFT_START,
  STEP_TRACKER_MOTOR_LEFT_START,
  STEP_WAIT_TRACKER_MOTOR_LEFT_DETECTED,
  STEP_TRACKER_MOTOR_LEFT_DETECTED,
  STEP_WAIT_TRACKER_MOTOR_LEFT_RETURN,
  STEP_TRACKER_MOTOR_LEFT_RETURN,


  STEP_WAIT_BUTTON_START,
  STEP_BUTTON_START,
};

#endif  // ENUM_STEP_HPP


